name: Build Windows EXE and Publish Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows-exe:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip wheel setuptools

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build with PyInstaller
        run: pyinstaller --clean --noconfirm SystemAudioCopilot.spec

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SystemAudioCopilot-windows-${{ github.ref_name }}
          path: dist/**

      - name: Publish release assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**

